---
name: Test

on:
  pull_request:
  push:

jobs:
  test_pebble:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
        with:
          # chartpress requires the full history
          fetch-depth: 0

      # ref: https://github.com/jupyterhub/action-k3s-helm
      - uses: jupyterhub/action-k3s-helm@v2
        with:
          k3s-version: ""
          helm-version: ""
          metrics-enabled: false
          traefik-enabled: false

      - uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Run tests
        run: |
          helm lint pebble --values ci/ci-values.yaml
          helm lint pebble --strict --values ci/ci-values.yaml
          helm template pebble ./pebble --values ci/ci-values.yaml --validate
          helm install pebble ./pebble --values ci/ci-values.yaml --wait --timeout 60s
          helm test pebble

      # ref: https://github.com/jupyterhub/action-k8s-namespace-report
      - name: Kubernetes namespace report
        uses: jupyterhub/action-k8s-namespace-report@v1
        if: always()
        with:
          important-workloads: pebble-test pebble-coredns-test deploy/pebble-coredns
